USE db_usuarios;

CREATE TABLE IF NOT EXISTS tb_usuarios (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL,
  rm VARCHAR(5) NOT NULL,
  loginprof VARCHAR(20) NOT NULL,
  senha CHAR(60) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;